### PR TITLE
(bugfix) /etc/rc.d/rc.rsyslogd: OS-native PID for decisions

### PR DESCRIPTION
**Pull request by desertwitch**
bugfix: multiple running _rsyslogd_ processes (e.g. spawned by Docker containers) caused the _rc.d_ script to think that the OS-native process was already running, resulting in startup or restart failure of the OSes daemon. the proposed changes make the script act on the OS-native PID file and not other unrelated processes by name.

-- Rysz (credits to Discord user _Brendann_ for noticing this issue)

### CODE REVIEW

**Comment by SimonFair** [comment]
@desertwitch We are looking to use the following on pgrep and killall to stop this type of issue in the RC files

killall --ns $$ sshd

**Comment by desertwitch** [comment]
> @desertwitch We are looking to use the following on pgrep and killall to stop this type of issue in the RC files
> 
> Example for sshd
> 
> killall --ns $$ sshd

Great idea with the namespaces, thanks @SimonFair , amended PR and backport to that solution. 💯

**Comment by desertwitch** [comment]
> @desertwitch We are looking to use the following on pgrep and killall to stop this type of issue in the RC files
> 
> Example for sshd
> 
> killall --ns $$ sshd

Great idea with the namespaces, thanks @SimonFair , amended PR and backport to that solution. 💯

**Comment by SimonFair** [comment]
LGTM

**Comment by limetech** [comment]
thx!

**Pull request merged**
