### PR TITLE
Do not flag mover messages

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by limetech** [comment]
re: Allow dot in user name

This might break something.  Refer to first answer here:
https://stackoverflow.com/questions/6949667/what-are-the-real-rules-for-linux-usernames-on-centos-6-and-rhel-6

Was there a request by someone to allow this?

**Comment by bergware** [comment]
_Was there a request by someone to allow this?_

Yes, see https://forums.unraid.net/topic/104434-change-adduser-restriction/?tab=comments#comment-964343

If not sure, I can revert this change.

**Comment by bergware** [comment]
Ok, I reverted this PR. Better safe than sorry!

**Comment by limetech** [comment]
thx.  Yes I think we can support this but it's something I'd rather introduce during a beta/rc series rather than add to stable.

**Pull request merged**
