### PR TITLE
When no array, hide disk shares

### PR DESCRIPTION
**Pull request by ljm42**

### CODE REVIEW

**Comment by johnnieblack** [comment]
Larry, won't this also hide the disk shares for pools?

**Comment by ljm42** [comment]
Pools don't have individual disk shares right? Just the array

**Comment by SimonFair** [comment]
All of my pools show in disk shares.

image

**Comment by ljm42** [comment]
Thanks, if Disk Shares are enabled I do Pools listed. Closing this, not a good idea

**Pull request closed without merging**
